'use client';
import { useMemo, useState } from 'react';
import { Activity, ArrowDown, ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, ChartPie, Check, ChevronDown, CircleHelp, FileText, Layers, LayoutDashboard, Play, RotateCcw, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp, Wallet, X } from 'lucide-react';
import { assets, defaults, metrics, optimize, checks, type Limits } from '../lib/optimizer';
import { createPlanPdf } from '../lib/plan-pdf';
const money = (n:number) => `₹${n.toFixed(2)} Cr`;
export default function Home(){
 const [weights,setWeights]=useState([35,25,20,10,7,3]);
 const [limits,setLimits]=useState<Limits>({...defaults});
 const [tab,setTab]=useState('Optimizer'); const [editor,setEditor]=useState(false); const [draft,setDraft]=useState(weights); const [error,setError]=useState('');
 const [run,setRun]=useState(true); const [notice,setNotice]=useState('');
 const current=useMemo(()=>metrics(weights),[weights]); const result=useMemo(()=>optimize(weights,limits),[weights,limits]);
 const target=run&&result.feasible?result.target:weights; const after=metrics(target); const rules=checks(weights,limits); const breaches=rules.filter(r=>!r.ok);
 const status=!run?'Ready to optimize':!result.feasible?'No feasible plan':result.hold?'HOLD recommended':'Rebalance recommended';
 const trades=weights.map((w,i)=>({asset:assets[i],delta:target[i]-w}));
 const ready=run&&result.feasible;
 const turnover=trades.reduce((sum,t)=>sum+Math.abs(t.delta),0)/2;
 const executionCost=trades.reduce((sum,t)=>sum+Math.abs(t.delta)*t.asset.cost/10000,0);
 const candidateHurdle=result.cost*limits.hurdle;
 const cleared=ready?checks(target,limits).filter(r=>r.ok).length:0;
 function update(key:keyof Limits,value:number){setLimits({...limits,[key]:value});setRun(false)}
 function exportPlan(){
  if(!run||!result.feasible){setNotice('Run optimization and obtain a feasible plan before exporting.');return}
  try {
   const data=createPlanPdf({weights:[...weights],target:[...target],limits:{...limits},hold:result.hold,candidateCost:result.cost,benefit:result.benefit,reasons:trades.map((t,i)=>reason(i,t.delta))});
   const url=URL.createObjectURL(new Blob([data as BlobPart],{type:'application/pdf'}));
   const a=document.createElement('a');a.href=url;a.download='capitaliq-rebalancing-plan.pdf';document.body.appendChild(a);a.click();a.remove();
   window.setTimeout(()=>URL.revokeObjectURL(url),60000);
   setNotice('PDF report downloaded. Open it in your browser or any PDF reader.');
  }catch{setNotice('The PDF could not be generated. Please run optimization and try again.');}
 }

 const reason=(i:number,d:number)=>Math.abs(d)<.001?'Existing allocation retained; no trade required.':d>0?(i===5?'Rebuild the liquidity buffer and meet the cash floor.':i===2?'Add lower-volatility exposure to reduce modeled tail risk.':'Improve diversification within the configured limits.'):(i<2?'Reduce combined equity exposure and modeled downside risk.':'Release capital for a more efficient risk allocation.');
 return <div className="app"><aside className="sidebar"><a className="brand" href="#"><span className="brand-icon"><Layers size={22}/></span>capital<span>IQ</span></a><div className="workspace"><span className="workspace-icon">N</span><div>Northstar Capital<small>Institutional workspace</small></div><ChevronDown size={14}/></div><p className="nav-label">WORKSPACE</p><nav>{[{name:'Optimizer',icon:SlidersHorizontal},{name:'Trade plan',icon:ArrowUpRight},{name:'Cost & benefit',icon:Activity},{name:'Decision notes',icon:FileText},{name:'Overview',icon:LayoutDashboard},{name:'Portfolio',icon:ChartPie},{name:'Risk controls',icon:ShieldCheck}].map(({name,icon:Icon})=><button aria-label={name} key={name} className={tab===name?'selected':''} onClick={()=>{setTab(name);document.getElementById(name==='Overview'?'context':name==='Cost & benefit'?'cost-benefit':name==='Risk controls'?'controls':name==='Trade plan'?'trades':name==='Decision notes'?'explanation':name==='Portfolio'?'allocation':'top')?.scrollIntoView({behavior:'smooth'})}}><Icon size={18}/>{name}{name==='Optimizer'&&<span className="new">MAIN</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-box"><span className="live-dot"/> HACKATHON DEMO<p>Smarter capital.<br/>Stronger controls.</p><small>Illustrative market assumptions</small></div><div className="profile"><span>AS</span><div>Alex Sharma<small>Portfolio manager</small></div><Settings2 size={16}/></div></div></aside>
 <main id="top"><header><div className="breadcrumb">Workspace <span>/</span> <b>Capital optimization</b></div><div className="header-right"><span className="demo-pill"><span className="live-dot"/> Demo environment</span><button aria-label="Show notifications" className="icon-button" onClick={()=>setNotice(`${breaches.length} active risk breaches. Review the Risk Control Center below.`)}><Bell size={18}/><i/></button><span className="avatar">AS</span></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">PERSON 3 / OPTIMIZATION & REBALANCING</div><h1>From allocation to action.</h1><p>A constraint-aware target. A cost-aware trade plan. A decision you can explain.</p></div><button className="button secondary" onClick={exportPlan}><ArrowDownToLine size={16}/> Export PDF</button></div>
 <div className="portfolio-toolbar"><div><span className="portfolio-symbol"><Wallet size={19}/></span><b>Multi-Asset Growth Portfolio</b><span className="tag">INR</span><span className="muted">6 asset classes</span></div><button className="text-button" onClick={()=>{setDraft([...weights]);setEditor(true);setError('')}}><Settings2 size={15}/> Edit portfolio</button></div>
 <div className="section-heading"><div><span className="eyebrow">MAIN SHOWCASE · FEATURES 11–20</span><h2><span className="heading-icon"><Sparkles size={19}/></span>Optimization result <span className="tag green">CONSTRAINT-AWARE</span></h2><p>Review the target, understand the trade-offs, then inspect every trade.</p></div><button className="button primary" onClick={()=>{setRun(true);setNotice('Optimization complete. Recommendations reflect your current inputs.')}}><Play size={15} fill="currentColor"/> Run optimization</button></div>
 <section className={'result-hero '+(!ready?'pending-result':'')} aria-live="polite"><div className="hero-decision"><span className="eyebrow">CONSTRAINED CAPITAL OPTIMIZER</span><h2>{status}</h2><p>{!run?'Inputs changed. Run optimization to refresh the recommendation.':!result.feasible?'No feasible candidate found. Adjust risk controls to generate a valid plan.':result.hold?'Keep your current holdings. The candidate does not justify the cost hurdle.':breaches.length?'Address current policy breaches with a feasible, fully allocated target.':'The modeled risk benefit clears the configured cost hurdle.'}</p><a href="#trades">Inspect BUY / SELL / HOLD plan <ArrowRight size={15}/></a></div><div className="hero-stats"><div><span>CONTROLS SATISFIED</span><b>{ready?cleared+' / 5':'—'}</b><small>{ready?'Verified against your mandate':'Awaiting valid result'}</small></div><div><span>ONE-WAY TURNOVER</span><b>{ready?turnover.toFixed(1)+'%':'—'}</b><small>Half of absolute allocation changes</small></div><div><span>IMPLEMENTATION COST</span><b>{ready?'₹'+(executionCost*100).toFixed(2):'—'} <small>{ready?'Lakh':''}</small></b><small>Both buys and sells included</small></div></div></section>
 <div className="outcome-strip"><div><span>TAIL RISK CHANGE</span><b>{ready?(after.cvar-current.cvar).toFixed(2)+' pp':'—'}</b><small>Annual 95% CVaR</small></div><div><span>LIQUIDITY CHANGE</span><b>{ready?((after.liquidity-current.liquidity)>=0?'+':'')+(after.liquidity-current.liquidity).toFixed(1)+' pp':'—'}</b><small>Liquid allocation</small></div><div className="return-sacrifice"><span>EXPECTED RETURN CHANGE</span><b>{ready?((after.ret-current.ret)>=0?'+':'')+(after.ret-current.ret).toFixed(2)+' pp':'—'}</b><small>Annual modeled return</small></div><div><span>SAFETY SCORE CHANGE</span><b>{ready?((after.score-current.score)>=0?'+':'')+(after.score-current.score).toFixed(0)+' points':'—'}</b><small>Demo safety heuristic</small></div></div>
 <div className="optimizer-grid"><section className="panel allocation-panel" id="allocation"><div className="panel-title"><div><h3>Current vs. optimized allocation</h3><p>Where your capital is, and where it could be.</p></div><span className="tag">% of portfolio</span></div><div className="chart-legend"><span><i style={{background:'#d5dee7'}}/>Current</span><span><i style={{background:'#158b72'}}/>Optimized</span></div><div className="allocation-chart">{assets.map((a,i)=><div className="chart-row" key={a.name}><span className="asset-label"><i style={{background:a.color}}/>{a.name}</span><div className="bar-pair"><div className="bar-track"><div className="bar current" style={{width:`${weights[i]}%`}}/><span>{weights[i].toFixed(1)}%</span></div><div className="bar-track"><div className="bar optimized" style={{width:`${target[i]}%`}}/><span className="green-text">{target[i].toFixed(1)}%</span></div></div><span className={`delta ${target[i]>weights[i]?'green-text':''}`}>{target[i]-weights[i]>0?'+':''}{(target[i]-weights[i]).toFixed(1)}<small>pp</small></span></div>)}</div><div className="chart-axis"><span>0%</span><span>20%</span><span>40%</span><span>60%</span><span>80%</span><span>100%</span></div><div className="panel-footer"><ShieldCheck size={15}/>{run&&result.feasible?'Optimized allocation satisfies all configured limits.':run?'No feasible candidate found. Review conflicting constraints.':'Inputs changed. Run optimization to refresh the plan.'}</div></section>
 <section className="panel decision-panel"><div className="panel-title"><div><h3>The decision, explained</h3><p>Risk, reward, and the cost in between.</p></div><Sparkles size={19} className="green-text"/></div><div className="recommendation"><span className="decision-label"><span className="live-dot"/> OPTIMIZER RECOMMENDATION</span><h2>{status}</h2><p>{!run?'Your constraints have changed. Run a new analysis to generate a fresh trade plan.':!result.feasible?'The search found no allocation satisfying every limit. Relax a constraint and try again.':result.hold?'The modeled risk benefit does not clear your cost-benefit hurdle. Retain current holdings.':breaches.length?'Restore policy compliance while balancing portfolio risk and implementation cost.':'Modeled risk reduction clears the configured transaction-cost hurdle.'}</p></div><div className="comparison"><div className="comparison-head"><span>PORTFOLIO IMPACT</span><span>BEFORE</span><span>AFTER</span></div>{[['Safety score',current.score.toFixed(0),after.score.toFixed(0)],['Expected return',`${current.ret.toFixed(2)}%`,`${after.ret.toFixed(2)}%`],['Volatility',`${current.vol.toFixed(2)}%`,`${after.vol.toFixed(2)}%`],['95% CVaR',`${current.cvar.toFixed(2)}%`,`${after.cvar.toFixed(2)}%`],['Liquidity',`${current.liquidity.toFixed(1)}%`,`${after.liquidity.toFixed(1)}%`]].map(row=><div key={row[0]}><span>{row[0]}</span><span>{row[1]}</span><b>{row[2]}</b></div>)}</div><div className="tradeoff"><ArrowDown size={17}/><p><b>{Math.max(0,current.cvar-after.cvar).toFixed(2)} pp less modeled tail risk</b><span>{after.ret<current.ret?`${(current.ret-after.ret).toFixed(2)} pp expected return sacrificed`:`${(after.ret-current.ret).toFixed(2)} pp expected return gained`}</span></p></div></section></div>
 <section className="panel trade-panel" id="trades"><div className="panel-title"><div><h3>Rebalancing execution plan <span className="tag">6 ASSETS</span></h3><p>Transparent actions. Every rupee accounted for.</p></div><span className="tag green">{!run?'Awaiting optimization':result.feasible?'Analysis complete':'No feasible plan'}</span></div><div className="table-scroll"><table><thead><tr><th>ASSET CLASS</th><th>ACTION</th><th>CURRENT → TARGET</th><th>TRADE VALUE</th><th>EST. COST</th><th>WHY THIS TRADE?</th></tr></thead><tbody>{trades.map((t,i)=><tr key={t.asset.name}><td><span className="asset-symbol" style={{color:t.asset.color,background:t.asset.color+'14'}}>{t.asset.short}</span><b>{t.asset.name}</b></td><td><span className={`action ${t.delta>.001?'buy':t.delta<-.001?'sell':'hold'}`}>{!run||!result.feasible?'—':t.delta>.001?'↗ BUY':t.delta<-.001?'↘ SELL':'— HOLD'}</span></td><td>{weights[i].toFixed(1)}% <span className="muted">→</span> <b>{target[i].toFixed(1)}%</b></td><td>{money(Math.abs(t.delta))}</td><td>₹{(Math.abs(t.delta)*10000000*t.asset.cost/10000).toLocaleString('en-IN',{maximumFractionDigits:0})}</td><td className="reason">{!run||!result.feasible?'Awaiting a feasible optimization result.':reason(i,t.delta)}</td></tr>)}</tbody></table></div><div className="trade-summary"><div><span>ONE-WAY TURNOVER <CircleHelp size={12}/></span><b>{(trades.reduce((s,t)=>s+Math.abs(t.delta),0)/2).toFixed(1)}%</b></div><div><span>GROSS TRADED VALUE</span><b>{money(trades.reduce((s,t)=>s+Math.abs(t.delta),0))}</b></div><div><span>TRANSACTION COST</span><b>₹{(trades.reduce((s,t)=>s+Math.abs(t.delta)*10000000*t.asset.cost/10000,0)/100000).toFixed(2)} <small>Lakh</small></b></div><div className="cost-note"><ShieldCheck size={23}/><p><b>Cost-aware by design</b><span>Policy breaches take priority over the HOLD hurdle.</span></p></div></div></section>
 <section className="panel cost-benefit-panel" id="cost-benefit"><div className="panel-title"><div><span className="eyebrow">COST-AWARE REBALANCING</span><h3>Is the rebalance worth its cost?</h3><p>A transparent HOLD check, with hard policy controls taking priority.</p></div><span className="tag green">{!ready?'PENDING':result.hold?'HOLD':breaches.length?'POLICY REMEDIATION':'BENEFIT CLEARS COST'}</span></div><div className="cost-equation"><div><span>CANDIDATE RISK BENEFIT</span><b>{ready?money(result.benefit):'—'}</b><small>Annual CVaR reduction × ₹100Cr</small></div><span className="equation-symbol">{ready?(result.benefit>candidateHurdle?'>':'≤'):'?'}</span><div><span>COST × HURDLE</span><b>{ready?money(candidateHurdle):'—'}</b><small>{ready?'₹'+(result.cost*100).toFixed(2)+' lakh × '+limits.hurdle+'×':'Run optimization to calculate'}</small></div><div className="hold-verdict"><ShieldCheck size={22}/><p><b>{!ready?'Awaiting a valid result':result.hold?'HOLD · retain current allocation':breaches.length?'REBALANCE · restore compliance':'REBALANCE · hurdle passed'}</b><span>{!ready?'Stale or infeasible results cannot authorize a trade plan.':result.hold?'Executable turnover and transaction costs are zero.':breaches.length?'Current breaches override the cost-based HOLD check.':'The compliant candidate provides sufficient modeled risk benefit.'}</span></p></div></div><div className="panel-footer">Risk benefit is a tail-loss proxy, not profit or realized savings. Candidate costs are shown here; the trade plan shows executable costs.</div></section>
 <div className="decision-showcase"><section className="panel" id="explanation"><div className="panel-title"><div><h3>Explainable decision engine</h3><p>An explanation you can take into the room.</p></div><FileText size={18}/></div><div className="notes"><span className="eyebrow">DECISION RATIONALE</span><p>{breaches.length?`The current portfolio breaches ${breaches.map(r=>r.name.toLowerCase()).join(', ')}. `:'The current allocation meets all configured risk controls. '}{run&&result.feasible?`${result.hold?'Retaining':'Moving to'} the recommended allocation changes modeled annual CVaR from ${current.cvar.toFixed(2)}% to ${after.cvar.toFixed(2)}% and liquid allocation from ${current.liquidity.toFixed(1)}% to ${after.liquidity.toFixed(1)}%. ${result.hold?'The candidate did not justify implementation costs.':'The displayed trades fund purchases through equal-value sales; costs are reported separately and reduce post-trade NAV.'}`:'Run optimization after adjusting your constraints to generate an actionable explanation.'}</p><details><summary>Model assumptions & methodology <ChevronDown size={14}/></summary><p>Illustrative annual returns and factor covariance; normal-model 95% VaR and CVaR over one year. Liquidity includes all assets except real estate. Safety score is a demo heuristic. Long-only allocation totals 100%. Search uses pairwise transfers at 1 percentage-point resolution; no global optimality guarantee.</p><p>One-way turnover = ½ × sum of absolute weight changes. Costs apply to both buys and sells using asset-specific basis points ({assets.map(a=>`${a.name}: ${a.cost}`).join('; ')}). Benefit proxy = reduction in annual CVaR × portfolio value. It is a risk proxy, not realized savings. HOLD if compliant and proxy benefit ≤ hurdle × costs. No live data, tax, or market-impact model.</p><p>Annual 95% VaR: {current.var.toFixed(2)}%. Largest holding: {Math.max(...weights).toFixed(1)}%. Weights are gross of estimated costs.</p></details></div></section></div>
 <section className="context-section" id="context"><div className="section-heading"><div><span className="eyebrow">SUPPORTING CONTEXT · FEATURES 01–10</span><h2>Portfolio health & risk controls</h2><p>The current portfolio and mandate behind the recommendation.</p></div></div> <section className="metrics-grid"><Metric title="TOTAL PORTFOLIO VALUE" value="₹100.00" unit="Cr" icon={<Wallet size={17}/>} foot="Fully allocated across 6 asset classes"/><Metric title="CAPITAL SAFETY SCORE" value={current.score.toFixed(0)} unit="/ 100" icon={<ShieldCheck size={17}/>} foot={current.score>=75?'Healthy · modeled safety score':'Needs attention · modeled safety score'} progress={current.score}/><Metric title="EXPECTED ANNUAL RETURN" value={current.ret.toFixed(2)} unit="%" icon={<TrendingUp size={17}/>} foot={`Sharpe ratio ${current.sharpe.toFixed(2)} · risk-free rate 5%`}/><Metric title="95% CVaR · ANNUAL" value={current.cvar.toFixed(2)} unit="%" icon={<Activity size={17}/>} foot={`Policy limit ≤ ${limits.cvar}% · modeled tail loss`} warning={current.cvar>limits.cvar}/></section>
 <div className={`alert ${breaches.length?'':'safe'}`}><ShieldCheck size={20}/><div><b>{breaches.length?`${breaches.length} risk controls need your attention`:'Your portfolio is within all configured limits'}</b><span>{breaches.length?breaches.slice(0,3).map(r=>r.name).join(' · '):'Run the optimizer to evaluate potential improvements after costs.'}</span></div><button onClick={()=>document.getElementById('controls')?.scrollIntoView({behavior:'smooth'})}>Review controls <ArrowRight size={15}/></button></div>
</section>
 <div className="bottom-grid"><section className="panel" id="controls"><div className="panel-title"><div><h3>Risk Control Center</h3><p>Your mandate. Enforced with every optimization.</p></div><SlidersHorizontal size={18}/></div><div className="controls">{([{key:'cash',name:'Minimum cash reserve',min:0,max:40,step:1},{key:'equity',name:'Maximum combined equity',min:0,max:100,step:1},{key:'cvar',name:'Maximum annual 95% CVaR',min:1,max:40,step:1},{key:'concentration',name:'Maximum single asset',min:10,max:100,step:1},{key:'liquidity',name:'Minimum liquid allocation',min:0,max:100,step:1},{key:'hurdle',name:'Benefit / cost hurdle',min:0,max:10,step:.5}] as const).map(c=><label className="control" key={c.key}><span>{c.name}</span><input aria-label={c.name} type="range" min={c.min} max={c.max} step={c.step} value={limits[c.key]} onChange={e=>update(c.key,Number(e.target.value))}/><b>{limits[c.key]}{c.key==='hurdle'?'×':'%'}</b></label>)}</div><div className="risk-chips">{rules.map(r=><span key={r.name} className={r.ok?'ok':'breach'}>{r.ok?<Check size={12}/>:<Activity size={12}/>} {r.name}: {r.ok?'Safe':'Critical'}</span>)}</div></section></div><footer><span><Layers size={14}/> capitalIQ <span>Intelligence behind every allocation.</span></span><span>DEMO DATA ONLY <i/> No trades are executed</span></footer></div></main>
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {editor&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="editor-title" onKeyDown={e=>{if(e.key==='Escape')setEditor(false)}}><div className="panel-title"><h2 id="editor-title">Edit demo portfolio</h2><button autoFocus className="icon-button" aria-label="Close editor" onClick={()=>setEditor(false)}><X size={20}/></button></div><p>Allocate ₹100Cr across six asset classes. Weights must total 100%.</p>{assets.map((a,i)=><label className="editor-row" key={a.name}>{a.name}<span><input type="number" min="0" max="100" step="1" value={draft[i]} onChange={e=>setDraft(draft.map((v,j)=>j===i?Number(e.target.value):v))}/>%</span></label>)}<p className={Math.abs(draft.reduce((s,v)=>s+v,0)-100)>.001?'red-text':'green-text'}>Total: {draft.reduce((s,v)=>s+v,0).toFixed(1)}%</p>{error&&<p role="alert" className="red-text">{error}</p>}<div className="modal-actions"><button className="button secondary" onClick={()=>setDraft([35,25,20,10,7,3])}><RotateCcw size={15}/> Reset demo</button><button className="button primary" onClick={()=>{if(draft.some(v=>!Number.isFinite(v)||v<0||v>100)||Math.abs(draft.reduce((s,v)=>s+v,0)-100)>.001){setError('Use non-negative allocations totaling exactly 100%.');return}setWeights([...draft]);setRun(false);setEditor(false)}}>Apply allocation</button></div></section></div>}
 </div>
}
function Metric({title,value,unit,icon,foot,progress,warning}:{title:string,value:string,unit:string,icon:React.ReactNode,foot:string,progress?:number,warning?:boolean}){return <section className="metric"><div className="metric-title">{title}{icon}</div><div className="metric-number">{value}<span>{unit}</span>{warning&&<span className="tag amber">Above limit</span>}</div>{progress!==undefined&&<div className="score-track"><div style={{width:`${progress}%`}}/></div>}<p className={warning?'amber-text':''}>{foot}</p></section>}
